### ISSUE TITLE
crash sdrpp

### ISSUE THREAD

**Issue by PE1DDA** [Sultan-papagani/sdrpp_rtlsdr_source#1]
Hello,

First of all, thank you for your excellent job on this modded DLL(s)
Just downloaded the new(er) version and tried to add the new source in the latest SDRpp nightly build (april 23th)
Unfortunately, when adding through the module manager, SDR++ crashes and closes.
the same goes for your "older"  version, I am on Windows 11 Pro 23H2 (x64)
Both versions work fine in the nightly build from april 4-th (that is the oldest nightly build I've got)

Can you reproduce the problem from your side and hopely solve it........?

Thank you for your trouble

73's
PE1DDA
Cees

**Comment by WB0OCV** [comment]
Greetings,
I noticed the same behavior with the two most recent updates to SDR++, and both the old and new versions of the modified dlls.  Both cause SDR++ to crash when trying ot install the new module.
One other thing I noticed is that the Zip-file for the new version does not contain the rtlsdr.dll file that the old Zip-file did.  Per the instructions, one is supposed to copy that file into the root folder for SDR++.  I'm using the older rtlsdr.dll file from the older Zip-file.
Thank you and 73
Ken -- WBØOCV
