### ISSUE TITLE
Cannot Compile rtlsdr-olddab on Any Debian Linux

### ISSUE THREAD

**Issue by ChrisDev8** [Sultan-papagani/sdrpp_rtlsdr_source#2]
# Cannot Compile Dependency => rtlsdr-olddab

I've been trying to compile your code from Sultan-papagani/rtlsdr-olddab for a working linux version of Sultan-papagani/sdrpp-rtlsdr-source but with no success. I'm not familiar with C or C++ so I have little idea on a fix for the bug. I've tried deleting librtlsdr from apt but to no avail. I've attached two log files. Also there is no issues page on the github for Sultan-papagani/rtlsdr-olddab and nobody seems to have the same issue likely because they are using windows. The original old-dab/rtlsdr works fine without any issues so likely your modifications have created the issue.

[debug_log.txt](https://github.com/user-attachments/files/15904944/debug_log.txt)
[normal_log.txt](https://github.com/user-attachments/files/15904945/normal_log.txt)

**Comment by Sultan-papagani** [comment]
i tried to use debian with virtual box for helping your problem but i failed 😅 

,dont bother with this source its buggy
im making a new one with no bugs, better performance at HF, no dependencies. etc.

but,
i think you should be able to compile normal old-dab and delete the line or two about reading DAGC and it should work(?) dagc will be removed anyways it has no purpose
